version: '{build}'
image: 'Visual Studio 2017'
platform: 'x64'

clone_folder: 'c:\gopath\src\github.com\drone-plugins\drone-base'
max_jobs: 1

environment:
  GOPATH: c:\gopath
  DOCKER_USERNAME:
    secure: '4YzzahbEiMZQJpOCOd1LAw=='
  DOCKER_PASSWORD:
    secure: 'VqO/G3Zfslu6zSLdwHKO+Q=='

install:
  - ps: |
      docker version
      go version
  - ps: |
      $env:Path = "c:\gopath\bin;$env:Path"

build_script:
  - ps: |
      docker build -f Dockerfile -t plugins/base:windows .

test_script:
  - ps: |
      Write-Host Nothing to test.

deploy_script:
  - ps: |
      $ErrorActionPreference = 'Stop';

      if ( $env:APPVEYOR_PULL_REQUEST_NUMBER ) {
        Write-Host Nothing to deploy.
      } else {
        if ( $env:APPVEYOR_REPO_BRANCH -eq 'windows' ) {
          echo $env:DOCKER_PASSWORD | docker login --username $env:DOCKER_USERNAME --password-stdin
          docker push plugins/base:windows
        } else {
          Write-Host Not windows branch.
        }
      }
