---
kind: pipeline
name: windows-1803

platform:
  os: windows
  arch: amd64
  version: 1803

steps:
- name: dryrun
  pull: always
  image: plugins/docker:windows-1803
  settings:
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1803
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/base
    tags: windows-1803
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-1803
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1803
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1803
    password:
      from_secret: docker_password
    repo: plugins/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
      exclude:
      - pull_request

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: dryrun
  pull: always
  image: plugins/docker:windows-1809
  settings:
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1809
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/base
    tags: windows-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-1809
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1809
    password:
      from_secret: docker_password
    repo: plugins/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
      exclude:
      - pull_request

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: notifications

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username

- name: microbadger
  pull: always
  image: plugins/webhook
  settings:
    urls:
      from_secret: microbadger_url

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"

depends_on:
- windows-1803
- windows-1809

...
