pipeline:
  publish:
    image: plugins/docker:17.05
    pull: true
    repo: plugins/base
    tags: [ multiarch ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_url ]
    when:
      branch: master
      event: push
      status: [ success ]
