pipeline:
  publish:
    image: plugins/docker:17.05
    pull: true
    repo: plugins/base
    tags: [ amd64 ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: amd64
      event: push

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_url ]
    when:
      branch: amd64
      event: push
      status: [ success ]
