# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-2004@sha256:42e413a0e48ed591c46719ff090ab9ac1dcce8b6cab5d4122b2714a3c49dbac1
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
