# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022@sha256:74f94e00c810ed628c713bd4a0a07f9ecded734e11c62b3d7136798b4104815a
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
