# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1903@sha256:fe9241bed73a4d8a223a07b79b83c058bd661d526078e44f2164f7967bc27fd9
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
