# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-2004@sha256:0738bb7329f2c0443454585fca9df72efc2af1b6a56bbee9c71fa6c9d390fa1a
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
