# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1903@sha256:81f6b1c06d3e064f1cc29415e87919fa9136564a958b7190ed1d5a17be7b9cb3
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
