# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1803@sha256:8be18aed46e343f6b9a599937583b90839c54227141e4121abf0f1387adfb336

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

USER ContainerAdministrator
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
