# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022@sha256:73498f7ca39fdee7f88ffe6cccf654a25801afe82c9e1e97e96f37a0a8620900
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
