# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1803@sha256:ba08a2c3e145d6638588319726587d1669a8f52607ec8f4af9d7adfa5ae29523

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
