# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1909@sha256:d6b98da02fb753a1f1a1ad94fd8994b348cdbcc2e828e6b3f863cfc1b521f1b9
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
