# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022@sha256:6eff7cba62940edeb777c9165c00f9a5ad0f6b12a481a454dfdcf873cf07edf5
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
