# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1909@sha256:429f9ebf206d8e94b4071168eab7938c483f8114601d75cc547fa318ad516e5f
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
