# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1909@sha256:e6dcc96560796d7cb7e5cc9fc73ad4c3355e54f1206a842eb72e757ca853e77f
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
