# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1809@sha256:d9b20f5403fd98a44c68844ee8be3d8174d5a9449b3825bce9771e59fb3956fc
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
