# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1809@sha256:3159abee4f8309b7c790bbfa898ccd94612e64f06029a49d543948bc181dc9cd
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
