# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-2004@sha256:292cc27a71ebc5d0f3d3b0b61a4a6a49460243a12c57112e9166c1a5c495d977
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
