# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1809@sha256:f88f5da0b24a583c368f78d60a166db5cd1721af03fe3173c15dcb758cf95719
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
